//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int idOrder { get; set; }
        public int Car { get; set; }
        public int Driver { get; set; }
        public int Client { get; set; }
        public string place1 { get; set; }
        public string place2 { get; set; }
        public double price { get; set; }
    
        public virtual Car Car1 { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Driver Driver1 { get; set; }
    }
}
